# Generated by Django 6.0.2 on 2026-02-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revolving_utilization', models.FloatField()),
                ('age', models.IntegerField()),
                ('late_30_59', models.IntegerField()),
                ('debt_ratio', models.FloatField()),
                ('monthly_income', models.FloatField()),
                ('open_credit_lines', models.IntegerField()),
                ('late_90', models.IntegerField()),
                ('real_estate_loans', models.IntegerField()),
                ('late_60_89', models.IntegerField()),
                ('dependents', models.IntegerField()),
                ('financial_stability_index', models.FloatField(blank=True, null=True)),
                ('payment_discipline_score', models.FloatField(blank=True, null=True)),
                ('debt_stress_index', models.FloatField(blank=True, null=True)),
                ('credit_utilization_risk', models.FloatField(blank=True, null=True)),
                ('credit_experience_score', models.FloatField(blank=True, null=True)),
                ('base_model_risk', models.FloatField(blank=True, null=True)),
                ('final_risk', models.FloatField(blank=True, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, max_length=20, null=True)),
                ('decision_explanation', models.TextField(blank=True, null=True)),
                ('actual_default', models.BooleanField(blank=True, help_text='Actual repayment outcome (for future model improvement)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('auc_score', models.FloatField()),
                ('fairness_ratio', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
